---
editor_options: 
  chunk_output_type: console
---

# Summarising agent paths over generations

```{r}
# load libraries
library(data.table)
library(glue)
library(stringr)

# source funs
source("R/fun_dist_disp.R")
source("R/fun_read_pos.R")
source("R/fun_steplength_timescale.R")
source("R/fun_read_config.R")
source("R/fun_wt_vals.R")
```

## Generation data

### Summarise distance and displacement

```{r}
paths = list.dirs(path = "data", recursive = F)
paths = paths[grep("sim", paths)]

# read data and summarise distance and displacement
data = lapply(paths, function(path) {
  
  df_ = read_data(path, gen_start = 0, gen_end = 240, gen_add = 249)
  
  df_ = df_[, list(paths = list(.SD)), by = c("id", "g")]
  df_[, c("displacement", "distance") := list(
    vapply(paths, get_displacement, FUN.VALUE = 1.0),
    vapply(paths, get_distance, FUN.VALUE = 1L)
  )]
  
  df_[, c("id", "g", "distance", "displacement")]
})
```

### Read parameters

```{r}
params = lapply(paths, read_config)

# add parameters
data = Map(function(df, p) {
  df[, names(p) := list(p["growth"], p["type"], p["rep_"])]
}, data, params)
```

### Get fitness

```{r}
# get wt and fitness data
wt_data = lapply(paths, get_wt_data, gen_start = 0, 
                 gen_end = 240, gen_add = 249,
                 n_agents = 100)

data = Map(data, wt_data, f = function(df_, wt_) {
  merge(df_, wt_, by.x = c("id", "g"), by.y = c("id", "gen"))
})

# bind and save
data = rbindlist(data)
# exclude gen 250
data = data[g < 250,]

# save
fwrite(data, file = "data/data_gens_dist_summary.csv")
```

## Long term movement data 

### List files and read data

needs to be made recursive over dirs.

```{r}
paths = list.dirs(path = "data", recursive = F)
paths = paths[grep("sim", paths)]

# loop over paths
for (path in paths) {
  df = read_data(path = path, gen_start = 250, gen_end = 250, gen_add = NULL)
  params = read_config(path)
  
  # round to interval
  df[, interval := round(t, digits = -3)]
  # nest by interval and id
  df = df[, list(paths = list(.SD)), by = c("id", "interval")]
  # get distance and displacement
  df[, c("displacement", "distance") := list(
    vapply(paths, get_displacement, FUN.VALUE = 1.0),
    vapply(paths, get_distance, FUN.VALUE = 1L)
  )]
  # add params
  df[, names(params) := list(params["growth"], params["type"], params["rep_"])]
  # remove path data
  df$paths = NULL
  
  # save data
  fwrite(df, file = glue("data/lt_tracks/lt_track_summary_{params['type']}_\\
         {params['growth']}_{params['rep_']}"))
}
```
