---
editor_options: 
  chunk_output_type: console
---

# Behavioural Mechanisms as Predictors of Movement Paths

```{r}
library(data.table)
library(lmerTest)
library(dplyr)

# custom funs
source("R/fun_wt_vals.R")
```

## Prepare data

```{r}
paths = list.files(path = "data/lt_tracks", full.names = T)

# read files
data = lapply(paths, fread)
# bind data
data = rbindlist(data)
```

summarise data over track

```{r}
# summarise data
data_summary = data[, list(
  mean_distance = mean(distance),
  sd_distance = sd(distance),
  mean_r = mean(mean_r)
), by = c("id", "interval", "growth", "type", "rep_",
          sprintf("wt_%i", seq(2, 4)))]
```

## Prepare data for model

### Determine strongest weight

```{r}
data_summary[, cluster := apply(
  data_summary[, c("wt_2", "wt_3", "wt_4")], 1, function(x){
    which.max(abs(x))
  })
]
data_summary[, cluster := case_when(
  cluster == 1 ~ "Nhnd",
  cluster == 2 ~ "Hand",
  cluster == 3 ~ "Prey"
)]
```

### Scale data

```{r}
# scale the weights using a tanh transform
data_summary[, sprintf("wt_%i", seq(2, 4)) := lapply(
  .SD, cut_wt_lower
), .SDcols = sprintf("wt_%i", seq(2, 4)),
by = c("interval", "growth", "type", "rep_", "cluster")]

# scale between 0 and 1
data_summary[, sprintf("wt_%i", seq(2, 4)) := lapply(
  .SD, scales::rescale
), .SDcols = sprintf("wt_%i", seq(2, 4)),
by = c("interval", "growth", "type", "rep_", "cluster")]

# scale the mean_distance and mean_r
data_summary[, c("mean_distance", "mean_r") := 
               lapply(.SD, scales::rescale), 
             .SDcols = c("mean_distance", "mean_r"),
          by = c("growth", "type", "rep_", "interval", "cluster")]

# save data
fwrite(data_summary, file = "data/data_for_idgambit.csv")
```

nest data

```{r}
data_summary = data_summary[, list(
  model_data = list(.SD)
), by = c("growth", "type", "rep_")]
```

## Fit GLM

```{r}
fit_model = function(df) {
  
  lmerTest::lmer(mean_distance ~ wt_2 + wt_3 + wt_4 + mean_r + 
        (1|id) + (1|interval), data = df)
  
}
```

```{r}
data_summary[, model := lapply(model_data, fit_model)]

# save model fits
save(data_summary, file = "data/data_model_fit_id_gambit.Rds")
```

## Model fits

```{r}
data_summary$model[[2]]|> summary()
a = data_summary$model[[1]]
```

### Summarise model fits

```{r}
model_fits = data_summary[, c("growth", "type", "rep_", "model")]
model_fits[, fit := lapply(model, function(df) {
  a = df |> summary() |> coefficients()
  b = as.data.table(a)
  b[, term := rownames(a)]
  b
})]

# unnest data
model_fits = model_fits[, unlist(fit, recursive = F),
           by = c("growth", "type", "rep_")]
setnames(model_fits, c("t value", "Pr(>|t|)"), c("t.value", "p.value"))

# save data
fwrite(model_fits, file = "data/data_idgambit_coefs.csv")
```
