
# The Individual Gambit

read data

```{r}
paths = list.dirs(path = "data", recursive = F)
paths = paths[grep("sim", paths)]
```

```{r}
# summarise data over a loop, no saving to ram
for (path in paths) {
  data = fread(file)

  # which data to read
  lt_data = glue("{path}/00250_pos.csv")
  param = lapply(path, read_config)

  data = data[, list(paths = list(.SD)), by = c("id", "g")]
  data[, c("displacement", "distance") := list(
    vapply(paths, get_displacement, FUN.VALUE = 1.0),
    vapply(paths, get_distance, FUN.VALUE = 1L)
  )]

  # get cdist data
  data[, cdist_data := lapply(
    paths, get_cumulative_distance
  )]
  
  data[, avg_speed_fit := lapply(cdist_data, get_avg_speed)]
  
  # remove cdist data
  data[, cdist_data := NULL]

  # first subsample and get steplengths
  data[, sl_ := lapply(paths, get_steplengths, tscale = 5)]
  
  # get nbinom fit
  data[, sl_fit := lapply(sl_, fit_sl_dist)]
  
  data[, sl_ := NULL]

  data[, sld_param := lapply(sl_fit, function(sl_fit_) {
    sl_fit_[[1]]
  })]
  
  data[, nb_mu := vapply(sld_param, `[`, 2, FUN.VALUE = 2.0)]
  
  data[, c("sl_fit", "sld_param") := NULL]

  data[, avg_speed := vapply(avg_speed_fit, `[`, 2, FUN.VALUE = 2.0)]
  data[, c("avg_speed_fit", "paths") := NULL]

  if (dir.exists("data/lt_tracks")) {
    dir.create("data/lt_tracks")
  } else {

    data[, names(param) := list(param["growth"], param["type"], param["rep_"])]
     fwrite(
       glue("data/lt_tracks/data_lt_{param["growth"]}_{param["type"]}_{param["rep_"]}")
     )
  }

}
```

## Link landscape metrics

### Read landscape

```{r}
source("R/fun_link_landscape.R")

# read landscape and link to movement
quality_data <- read_landscape(
  "data/data_parameters/kernels32.png"
)

item_data = read_landscape(
  "data/data"
)
```

### Merge landscape data and path

```{r}
data = lapply(data, function(df) {
  df[, land_summary := lapply(
    paths, get_path_env_summary, land_data = quality_data
  )]
})
```