---
editor_options: 
  chunk_output_type: console
---

# Summarising agent paths over generations

```{r}
# load libraries
library(data.table)
library(glue)
library(stringr)

# source funs
source("R/fun_dist_disp.R")
source("R/fun_read_pos.R")
source("R/fun_steplength_timescale.R")
source("R/fun_read_config.R")
```

## List files and read data

needs to be made recursive over dirs.

```{r}
paths = list.dirs(path = "data", recursive = F)
paths = paths[grep("sim", paths)]
# paths = c("data")

# read data
data = lapply(paths, read_data, gen_start = 0, gen_end = 190)
```

## Read parameters

```{r}
params = lapply(paths, read_config)
```


## Get distance and displacement

```{r}
# get distance and displacement
data = lapply(data, function(df) {
  df = df[, list(paths = list(.SD)), by = c("id", "g")]
  df[, c("displacement", "distance") := list(
    vapply(paths, get_displacement, FUN.VALUE = 1.0),
    vapply(paths, get_distance, FUN.VALUE = 1L)
  )]
  
  df
})
```

## Get cumulative distance and avg speed

```{r}
# get fit as list col
data = lapply(data, function(df) {
  assertthat::assert_that(
    "paths" %in% names(df), 
    msg = "paths df listcol missing"
  )
  
  # get cdist data
  df[, cdist_data := lapply(
    paths, get_cumulative_distance
  )]
  
  df[, avg_speed_fit := lapply(cdist_data, get_avg_speed)]
  
  # remove cdist data
  df[, cdist_data := NULL]
  
  df
})
```

## Fit a neg binom distribution to step lengths

### Fit distribution

```{r}
data = lapply(data, function(df) {
  
  # first subsample and get steplengths
  df[, sl_ := lapply(paths, get_steplengths, tscale = 5)]
  
  # get nbinom fit
  df[, sl_fit := lapply(sl_, fit_sl_dist)]
  
  df[, sl_ := NULL]
  
  df
})
```

### Get distribution parameters

```{r}
data = lapply(data, function(df) {
  df[, sld_param := lapply(sl_fit, function(sl_fit_) {
    sl_fit_[[1]]
  })]
  
  df[, nb_mu := vapply(sld_param, `[`, 2, FUN.VALUE = 2.0)]
  
  df[, c("sl_fit", "sld_param") := NULL]
  
})

```

## Get final data

```{r}
# remove path data
data = lapply(data, function(df) {
  df[, avg_speed := vapply(avg_speed_fit, `[`, 2, FUN.VALUE = 2.0)]
  df[, c("avg_speed_fit", "paths") := NULL]
})

# add parameters
data = Map(function(df, p) {
  df[, names(p) := list(p["growth"], p["type"], p["rep_"])]
}, data, params)

# bind list
data = rbindlist(data)

# save data
fwrite(data, file = "data/data_path_summaries.csv")
```
