---
editor_options: 
  chunk_output_type: console
---

# Plot variation within and between scenarios

```{r}
library(data.table)
library(ggplot2)
library(colorspace)
library(patchwork)

# cut wt fun
source("R/fun_wt_vals.R")
```

## Figures for movement paths

```{r}
data = fread("data/data_lt_plot.csv")[growth %in% c(0.01, 0.03) & 
                                        interval %in% c(3000, 6000),]
```

```{r}
data = split(data, by = c("type"))
```

```{r}
label_interval = c(
  # "1000" = "T:   500 - 1,500",
  "3000" = "T: 2,500 - 3,500",
  "6000" = "T: 5,500 - 6,500"
  # "8000" = "T: 7,500 - 8,500"
)

make_id_plots = function(df, type) {
  ggplot(df)+
    geom_hline(
      yintercept = 0, size = 0.1, col = "grey",
      lty = 2
    )+
    geom_vline(
      xintercept = 0, size = 0.1, col = "grey",
      lty = 2
    )+
  geom_path(
    aes(x_wrap, y_wrap,
        group = interaction(id, interval),
        col = factor(id)),
    show.legend = F
  )+
  scale_color_discrete_sequential(
    palette = "Batlow"
  )+
  facet_grid(
    growth ~ interval,
    # ncol = 2,
    labeller = labeller(
      interval = label_interval,
      growth = label_both
    ),
    switch = "y"
  )+
  coord_cartesian(
    xlim = c(-70, 70),
    ylim = c(-70, 70),
    expand = F
  )+
  theme_minimal(base_size = 10)+
  theme(
    strip.text = element_text(
      face = "italic"
    ),
    strip.background = element_rect(
      fill = "grey90",
      colour = "transparent"
    ),
    axis.title = element_blank(),
    # axis.ticks = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(
      linetype = 1, size = 0.2
    ),
    panel.border = element_rect(
      colour = "grey",
      fill = NA,
      size = 0.1
    )
  )
}
```


```{r}
plots = Map(data, names(data), f = make_id_plots)

plot_move = wrap_plots(
  plots[c("exploit", "interf")],
  ncol = 1
)
```

## Figures for path statistics

### Get data and cluster by strongest move weight

```{r}
# get weight data
data_wt = fread("data/data_lt_wt_gens.csv")[growth == 0.01,]

# get path summaries
paths = list.files(path = "data/lt_tracks", full.names = T)
# read files
data_stats = lapply(paths, fread)
# bind data
data_stats = rbindlist(data_stats)

# link to data_stats
data_stats = merge(data_stats, data_wt)

# class agents on wights
data_stats[, cluster := apply(
  data_stats[, c("wt_2", "wt_3", "wt_4")], 1, function(x){
    which.max(abs(x))
  })
]
data_stats[, cluster := dplyr::case_when(
  cluster == 1 ~ "Nhnd",
  cluster == 2 ~ "Hand",
  cluster == 3 ~ "Prey"
)]
data_stats[, cluster := factor(cluster, levels = c("Prey", "Hand", "Nhnd"))]
```

### Make plot

```{r}
plot_dist_hist =
  ggplot(data_stats[interval %in% c(1000, 3000, 6000, 8000) 
                    & type != "random" & rep_ == 2])+
  geom_histogram(
    aes(
      distance,
      fill = cluster
    ),
    alpha = 0.9,
    bins = 20,
    position = "identity"
  )+
  scale_fill_manual(
    values = c(
      "Prey" = "darkgreen",
      "Nhnd" = "indianred1",
      "Hand" = "steelblue"
    ),
    breaks = c("Prey", "Hand", "Nhnd"),
    labels = c("sP", "sH", "sN")
  )+
  facet_wrap(~ type, ncol = 1, scales = "free_x",
             labeller = labeller(
               type = c(
                 "exploit" = "Exploit. comp.",
                 "interf" = "Interf. comp."
               )
             )
  )+
  theme_classic(base_size = 10)+
  theme(
    legend.position = "top",
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 8),
    legend.key.width = unit(1, "mm"),
    legend.key.height = unit(1, "mm"),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    panel.grid.minor = element_blank()
  )+
  coord_cartesian(
    expand = F,
    xlim = c(200, 800)
  )+
  labs(
    y = "# Tracks",
    x = "Distance",
    fill = "Strongest weight"
  )
```

## Plot weights distribution

```{r}
# read data
wt_data = fread("data/data_lt_wt_gens.csv")
wt_data = wt_data[, c("id", "growth", "type", "rep_", 
                      sprintf("wt_%i", c(2, 3, 4)))]

setnames(wt_data, old = c("wt_2", "wt_3", "wt_4"), 
         new = c("sN", "sH", "sP"))
wt_data = melt(wt_data, id.vars = c("id", "growth", "type", "rep_"))

# scale wts
wt_data[, value := cut_wt_lower(value, steps = 100, scale = 20)]

wt_data = wt_data[, list(pW = .N / 1000), by = c("growth", "type", "rep_", "variable", "value")]
wt_data[, col := dplyr::case_when(
  variable == "sN" ~ "darkred",
  variable == "sH" ~ "steelblue",
  variable == "sP" ~ "darkgreen"
)]
wt_data[, col := scales::alpha(col, pW*10)]
```

```{r}
plot_wt_dist =
  ggplot(wt_data[growth == 0.01 & 
                   type != "random" & 
                   rep_ == 2 &
                   pW >= 0.01])+
  geom_hline(
    yintercept = 0, lty = 2,
    col = "grey"
  )+
  geom_tile(
    aes(
      variable, value,
      fill = col
    ),
    width = 0.8,
    show.legend = T
  )+
  scale_fill_identity()+
  theme_classic(
    base_size = 10
  )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    )
  )+
  facet_wrap(~type, scales = "free_y", ncol = 2,
             labeller = labeller(
               type = c(
                 "exploit" = "Exploit. comp.",
                 "interf" = "Interf. comp."
               )
             )
  )+
  coord_cartesian(ylim = c(-1, 1))+
  labs(
    x = "Movement weight",
    y = "Scaled weight value"
  )
```


## Wrap all plots

```{r}
fig_id_var =
  wrap_plots(
    plot_move,
    plot_wt_dist,
    plot_dist_hist,
    ncol = 2,
    design = "AAABB\nAAACC"
  ) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(face = "bold")
  )

ggsave(
  plot = fig_id_var,
  filename = "figures/fig_id_variation_distance.png",
  width = 6,
  height = 8
)
```

