---
editor_options: 
  chunk_output_type: console
---

# Plot variation within and between scenarios

```{r}
library(data.table)
library(ggplot2)
library(colorspace)
library(patchwork)

# cut wt fun
source("R/fun_wt_vals.R")
```

## Figure functional variation

```{r}
data_sc_wt = fread("data/data_lt_wts_scaled.csv")
data_sc_wt = data_sc_wt[growth %in% c(0.01, 0.03) & rep_ == 2]

# assign strategy
data_sc_wt[, agent_strategy := dplyr::case_when(
  wt_4 > 0.6 ~ "prey tracking",
  abs(wt_4 - wt_3) < 0.1 ~ "prey and handler tracking",
  wt_3 > 0.5 ~ "handler tracking",
  wt_3 < -0.5 ~ "handler avoiding",
  wt_2 > 0.5 ~ "non-handler tracking",
  wt_2 < -0.5 ~ "non-handler avoiding",
  T ~ NA_character_
)]
```

```{r}
# plots = lapply(data_sc_wt, function(df) {
plot_scaled_wt = 
  ggplot(data_sc_wt)+
    geom_hline(
      yintercept = 0, size = 0.1,
      col = "grey"
    )+
    geom_vline(
      xintercept = 0, size = 0.1,
      col = "grey"
    )+
    geom_abline(
      slope = c(-1, 1),
      intercept = c(1, -1),
      col = "grey",
      lty = 2,
      size = 0.1
    )+
    geom_jitter(
      aes(wt_4, wt_3, fill = wt_2),
      shape = 21, col = alpha("grey30", 0.1),
      size = 2,
      show.legend = T,
      alpha = 0.3
    )+
    geom_text(
      data = data.table(
        x = c(1, 0.1, 0.1),
        y = c(0, 1, -1),
        strat = c("Prey tracking", "Handler tracking",  "Handler avoiding"),
        angle = c(90, 0, 0)
      ),
      aes(x, y, label = strat, angle = angle),      
      size = 3,
      col = "grey30",
      hjust = "inward",
      fontface = "italic"
    )+
    scale_fill_continuous_diverging(
      palette = "Blue-Red 3", 
      rev = T,
      l2 = 90,
      l1 = 50,
      limits = c(-1, 1),
      breaks = c(-1, 1),
      labels = c("Non-handler avoiding", "Non-handler tracking"),
      alpha = 1
    )+
    scale_x_continuous(
      # trans = ggallin::ssqrt_trans
    )+
    scale_y_continuous(
      # trans = ggallin::ssqrt_trans
    )+
    facet_wrap(
      type ~ growth, 
      ncol = 2, 
      labeller = labeller(
        .multi_line = F,
        growth = label_both,
        type = c(
          "exploit" = "Exploit. comp.",
          "interf" = "Interf. comp."
        )
      )
    )+
    coord_cartesian(
      expand = T,
      xlim = c(-0, 1),
      ylim = c(-1, 1)
    )+
    theme_classic(
      base_size = 10
    )+
    theme(
      panel.grid.minor = element_blank(),
      panel.border = element_rect(
        colour = "grey",
        fill = NA,
        size = 0.1
      ),
      strip.background = element_blank(),
      strip.text = element_text(
        face = "italic"
      ),
      legend.position = "top",
      legend.key.height = unit(1, "mm"),
      legend.background = element_blank()
    )+
    labs(
      x = "sP",
      y = "sH",
      fill = NULL
    )+
    guides(
      fill = guide_colorbar(override.aes = list(alpha = 1))
    )
```

## Figures for movement paths

```{r}
data = fread("data/data_lt_plot.csv")[growth %in% c(0.01, 0.03) & 
                                        interval %in% c(3, 6),]

# select 2 agents per strategy
data[, uid := id %in% first(unique(id)), by = c("growth", "type", "agent_strategy")]
data = data[(uid),]

# remove some strategies
data = data[
  agent_strategy %in% 
    c("prey tracking", "handler tracking", "non-handler avoiding",
      "prey and handler tracking")
]
```

```{r}
data = split(data, by = "type")

plot_move = lapply(data, function(df) {  
  ggplot(df)+
    geom_path(
      aes(
        x_wrap, y_wrap, 
        group = interaction(id, interval, growth, rep_),
        col = agent_strategy
      ),
      show.legend = T
    )+
    scale_color_discrete_sequential(
      palette = "Batlow",
      labels = c(
        "prey tracking" = "Prey tracking",
        "handler tracking" = "Handler tracking",
        "prey and handler tracking" = "Prey & handler tracking",
        "non-handler avoiding" = "N. handler avoiding"
      )
    )+
    facet_grid(
      growth ~ interval, 
      labeller = labeller(
        .multi_line = F,
        agent_strategy = c(
          "prey tracking" = "Prey tracking",
          "handler tracking" = "Handler tracking",
          "prey and handler tracking" = "Prey & handler tracking",
          "non-handler avoiding" = "N. handler avoiding"
        ),
        growth = label_both,
        interval = c(
          "3" = "T: 3,000 - 4,000",
          "6" = "T: 6,000 - 7,000"
        )
      )
    )+
    theme_minimal(base_size = 10)+
    theme(
      legend.position = "top",
      strip.text = element_text(
        face = "italic"
      ),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      # legend.key.width = unit(2, "mm"),
      legend.key.height = unit(2, "mm"),
      strip.background = element_blank(),
      axis.title = element_blank(),
      # axis.ticks = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(
        linetype = 1, size = 0.2
      ),
      panel.border = element_rect(
        colour = "grey",
        fill = NA,
        size = 0.1
      )
    )+
    coord_cartesian(
      # xlim = c(-60, 60),
      # ylim = c(-60, 60)
    )+
    guides(
      colour = guide_legend(override.aes = list(
        size = 2
      ),
      nrow = 2, byrow = T, ncol = 2
      )
    )+
    labs(
      colour = NULL
    )
})

wrap_plots(
  plot_move,
  design = "AA\nBB",
  ncol = 1
)
```

## Figure movement distance distribution

```{r}
# get path summaries
paths = list.files(path = "data/lt_tracks", full.names = T)
# read files
data_stats = lapply(paths, fread)
# bind data
data_stats = rbindlist(data_stats)

# link to data_stats
data_stats = merge(data_stats[, !(c("wt_2", "wt_3", "wt_4"))], data_sc_wt, 
                   by = c("id", "growth", "type", "rep_", "intake", "gen"))
```

### Make plot

```{r}
plot_dist_hist =
  ggplot(data_stats[type != "random" &
    agent_strategy %in% c("handler tracking", 
      "prey tracking", "prey and handler tracking", "non-handler avoiding")  
  ])+
  stat_density(
    geom = "line",
    aes(
      x = distance, y = ..density..,
      col = agent_strategy
    ),
    position = "identity"
  )+
  scale_color_discrete_sequential(
    palette = "Batlow",
    labels = c(
      "prey tracking" = "Prey tracking",
      "handler tracking" = "Handler tracking",
      "prey and handler tracking" = "Prey & handler tracking",
      "non-handler avoiding" = "N. handler avoiding"
    )
  )+
  facet_wrap(type ~ growth, scales = "free_x",
             labeller = labeller(
               .multi_line = F,
               growth = label_both,
               type = c(
                 "exploit" = "Exploit. comp.",
                 "interf" = "Interf. comp."
               )
             )
  )+
  theme_classic(base_size = 10)+
  theme(
    legend.position = "top",
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 8),
    # legend.key.width = unit(2, "mm"),
    legend.key.height = unit(1, "mm"),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    panel.grid.minor = element_blank()
  )+
  coord_cartesian(
    expand = F,
    xlim = c(0, 100)
  )+
  guides(
    colour = guide_legend(override.aes = list(
      size = 2
    ),
    nrow = 2, byrow = T, ncol = 2
    )
  )+
  labs(
    colour = NULL,
    y = "Tracks (density)",
    x = "Distance"
  )
```

## Wrap all plots

```{r}
fig_id_var =
  wrap_plots(
    plot_scaled_wt,
    plot_move[[1]],
    plot_move[[2]],
    plot_dist_hist,
    design = "AABB\nDDCC"
  ) +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(face = "bold")
  )

ggsave(
  plot = fig_id_var,
  filename = "figures/fig_id_variation_distance.png",
  width = 190,
  height = 210,
  unit = "mm"
)
```

