---
editor_options: 
  chunk_output_type: console
---

# Plot SSF coefficients _vs_ agent weights

```{r}
library(data.table)
library(ggplot2)
library(colorspace)
library(patchwork)

# cut wt fun
source("R/fun_wt_vals.R")
```

## Read data

```{r}
paths = list.files("data/ssf_fits", full.names = T)
data = lapply(paths, fread)

data = rbindlist(data)
data = data[growth %in% c(0.01, 0.03)]
```

## Read agent weights

```{r}
wt_data = fread("data/data_lt_wts_scaled.csv")

wt_data[, move_strategy := dplyr::case_when(
  wt_4 > 0.6 ~ "prey tracking",
  ((wt_4 > 0) & (wt_3 > 0) & (abs(wt_4 - wt_3) < 0.1))  ~ "prey and handler tracking",
  wt_3 > 0.5 ~ "handler tracking",
  wt_3 < -0.5 ~ "handler avoiding",
  wt_2 > 0.5 ~ "non-handler tracking",
  wt_2 < -0.5 ~ "non-handler avoiding",
  T ~ "other"
)]

wt_data[, move_strategy := factor(
  move_strategy, 
  levels = c(
    "prey tracking",
    "handler tracking",
    "prey and handler tracking",
    "non-handler avoiding",
    "handler avoiding",
    "other"
  )
)
]
```

## Link coefficients and weights

```{r}
# select only significant predictors
data = data[p.value <= 0.05, !(c("std.error", "statistic"))]
data = data[, !("p.value")]

data[, term := dplyr::case_when(
  term == "cell_r" ~ "ssf_R"
)]

data = dcast(data, id + growth + type + rep_ ~ term, value.var = "estimate")

data = merge(data, wt_data, 
             by.x = c("id", "growth", "rep_", "type"), 
             by.y = c("id", "growth", "rep_", "type"),
             all.x = T, all.y = F)

data = data[id < 100,]

data = split(data, by = "type")
data = data[c("exploit", "obligate")]
```

```{r}
plot_ssf_hist = lapply(data, function(df) {
  ggplot(df)+
    geom_hline(
      yintercept = 0,
      lty = 2,
      col = 2
    )+
    ggdist::stat_histinterval(
      aes(
        factor(growth), ssf_R,
          fill = comp_strat
      ),
      col = "grey20",
      # outline_bars = FALSE,
      # binwidth = 0.2,
      alpha = 0.7,
      position = position_nudge(x = 0.0),
      point_colour = NA
    )+
    scale_fill_manual(
      values = c(
        "forager" = "darkseagreen",
        "klept" = "brown"
      ),
      labels = c(
        "forager" = "Forager",
        "klept" = "Kleptoparasite"
      )
    )+
    coord_flip(
      expand = F,
      xlim = c(0.8, NA),
      ylim = c(-2, 10)
    )+
    theme_test(
      base_size = 8
    )+
    theme(
      axis.title.x = ggtext::element_markdown(),
      axis.title.y = ggtext::element_markdown(),
      axis.text.y = element_text(
        angle = 90,
        hjust = 0.5
      ),
      legend.position = "top",
      legend.title = element_text(face = "bold"),
      legend.key.height = unit(2, "mm")
    )+
    labs(
      y = "Estimated relative selection for <i>r<i>",
      x = "Landscape productivity *r<sub>max</sub>*",
      fill = "Competitive strategy",
      colour = "Movement strategy"
    )+
    guides(
      fill = guide_legend(ncol = 2, title.position = "top"),
      colour = guide_legend(ncol = 2, title.position = "top", 
                            override.aes = list(size = 2))
    )
})

plot_ssf_hist =
  wrap_plots(
  plot_ssf_hist, guides = "collect"
)+
  plot_layout(
    tag_level = "new"
  )
```

```{r}
plot_ssf_box = lapply(data, function(df) {
  ggplot(df[move_strategy %in% c(
        "prey tracking",
        "handler tracking",
        "prey and handler tracking",
        "non-handler avoiding",
        "handler avoiding",
        "other"
      )])+
    geom_hline(
      yintercept = 0,
      lty = 2,
      col = 2
    )+
    geom_jitter(
      aes(
        move_strategy, ssf_R, col = move_strategy
      ),
      size = 0.2,
      width = 0.2,
      alpha = 0.4
    )+
    geom_boxplot(
      aes(
        move_strategy, ssf_R,
      ),
      width = 0.2,
      fill = alpha("grey", 0.2), 
      outlier.colour = NA
    )+
    scale_colour_manual(
      values = c(
        "prey tracking" = "seagreen",
        "prey and handler tracking" = "royalblue",
        "non-handler avoiding" = "red",
        "handler avoiding" = "orange",
        "handler tracking" = "lightblue",
        "other" = "lightgrey",
        "NA" = "transparent"
      ),
      breaks = c(
        "prey tracking",
        "handler tracking",
        "prey and handler tracking",
        "non-handler avoiding",
        "handler avoiding",
        "other"
      )
    )+
    scale_x_discrete(
      breaks = c(
        "prey tracking",
        "handler tracking",
        "prey and handler tracking",
        "non-handler avoiding",
        "handler avoiding",
        "other"
      )
    )+
    facet_grid(
      ~ comp_strat, 
      # ncol = 2, 
      labeller = labeller(
        .multi_line = F,
        growth = label_both,
        comp_strat = c(
          "forager" = "Foragers",
          "klept" = "Kleptoparasites"
        )
      )
    )+
    theme_test(
      base_size = 8
    )+
    theme(
      strip.background = element_blank(),
      strip.text = element_text(
        face = "italic"
      ),
      axis.title.x = ggtext::element_markdown(),
      axis.title.y = ggtext::element_markdown(),
      axis.text.x = element_blank(),
      axis.text.y = element_text(
        angle = 90,
        hjust = 0.5
      ),
      legend.position = "top",
      legend.title = element_text(face = "bold"),
      legend.key.height = unit(2, "mm")
    )+
    coord_cartesian(
      expand = F,
      # xlim = c(0.8, NA),
      ylim = c(-2, 10)
    )+
    labs(
      y = "Estimated relative selection for <i>r<i>",
      x = "Movement strategy",
      fill = "Competitive strategy",
      colour = "Movement strategy"
    )+
    guides(
      colour = guide_legend(ncol = 3, title.position = "top", 
                            override.aes = list(size = 2))
    )
})

plot_ssf_box = wrap_plots(
  plot_ssf_box, guides = "collect"
) +
  plot_layout(
    tag_level = "new"
  )
```

```{r}
plot_ssf = wrap_plots(
  plot_ssf_hist,
  plot_ssf_box,
  ncol = 1
)&
  plot_annotation(
    tag_levels = c("A", 1)
  )&
  theme(
    plot.tag = element_text(
      face = "bold"
    ),
    legend.position = "bottom"
  )

ggsave(
  plot_ssf,
  filename = "figures/fig_05.png",
  width = 170,
  height = 150, units = "mm"
)
```

