---
editor_options: 
  chunk_output_type: console
---

# Figure functional variation

```{r}
library(data.table)
library(ggplot2)
library(patchwork)
library(colorspace)
```

```{r}
data_sc_wt = fread("data/data_lt_wts_scaled.csv")
data_sc_wt = data_sc_wt[growth %in% c(0.01, 0.03) & rep_ == 2]

# assign strategy
data_sc_wt[, agent_strategy := dplyr::case_when(
  wt_4 > 0.6 ~ "prey tracking",
  abs(wt_4 - wt_3) < 0.1 ~ "prey and handler tracking",
  wt_3 > 0.5 ~ "handler tracking",
  wt_3 < -0.5 ~ "handler avoiding",
  wt_2 > 0.5 ~ "non-handler tracking",
  wt_2 < -0.5 ~ "non-handler avoiding",
  T ~ NA_character_
)]
```

```{r}
# plots = lapply(data_sc_wt, function(df) {
plot_scaled_wt = 
  ggplot(data_sc_wt)+
    geom_hline(
      yintercept = 0, # size = 0.2,
      col = "grey"
    )+
    geom_vline(
      xintercept = 0, # size = 0.2,
      col = "grey"
    )+
    geom_abline(
      slope = c(-1, 1),
      intercept = c(1, -1),
      col = "grey",
      lty = 2,
      size = 0.5
    )+
    geom_jitter(
      aes(wt_4, wt_3, fill = wt_2),
      shape = 21, col = alpha("grey30", 0.1),
      size = 2,
      show.legend = T,
      alpha = 0.3
    )+
    geom_text(
      data = data.table(
        x = c(1, 0.1, 0.1),
        y = c(0, 1, -1),
        strat = c("Prey tracking", "Handler tracking",  "Handler avoiding"),
        angle = c(90, 0, 0)
      ),
      aes(x, y, label = strat, angle = angle),      
      size = 3,
      col = "grey30",
      hjust = "inward",
      fontface = "italic"
    )+
    scale_fill_continuous_diverging(
      palette = "Blue-Red 3", 
      rev = T,
      l2 = 90,
      l1 = 50,
      limits = c(-1, 1),
      breaks = c(-1, 1),
      labels = c("Non-handler avoiding", "Non-handler tracking"),
      alpha = 1
    )+
    scale_x_continuous(
      # trans = ggallin::ssqrt_trans
    )+
    scale_y_continuous(
      # trans = ggallin::ssqrt_trans
    )+
    facet_wrap(
      type ~ growth, 
      ncol = 2, 
      labeller = labeller(
        .multi_line = F,
        growth = label_both,
        type = c(
          "exploit" = "Exploit. comp.",
          "interf" = "Interf. comp."
        )
      )
    )+
    coord_cartesian(
      expand = T,
      xlim = c(-0, 1),
      ylim = c(-1, 1)
    )+
    theme_classic(
      base_size = 10
    )+
    theme(
      panel.grid.minor = element_blank(),
      panel.border = element_rect(
        colour = "grey",
        fill = NA,
        size = 0.1
      ),
      strip.background = element_blank(),
      strip.text = element_text(
        face = "italic"
      ),
      legend.position = "top",
      legend.key.height = unit(1, "mm"),
      legend.background = element_blank()
    )+
    labs(
      x = "sP",
      y = "sH",
      fill = NULL
    )+
    guides(
      fill = guide_colorbar(override.aes = list(alpha = 1))
    )

# save plot
ggsave(
  plot_scaled_wt,
  filename = "figures/fig_scaled_wts.png",
  height = 5.25,
  width = 5
)
```
